services: 
   - type: web
     name: n8n
     runtime: docker
     env: docker
     plan: free
     envVars:
      # Добавьте эти переменные для настройки URL
       - key: N8N_BASIC_AUTH_ACTIVE
         value: true
       - key: N8N_BASIC_AUTH_USER
         value: username
       - key: N8N_BASIC_AUTH_PASSWORD
         value: password
       - key: N8N_HOST
         value: N8N-Host-Value
       - key: N8N_PROTOCOL
         value: N8N-Protocol-Value
       - key: N8N_PORT
         value: N8N-Port-Value
       - key: WEBHOOK_TUNNEL_URL
         value: N8N-Tunnel-Value
       - key: WEBHOOK_URL
         value: N8N-Url-Value
      # Добавьте эти переменные для настройки URL
       - key: DB_TYPE
         value: postgresdb
       - key: DB_POSTGRESDB_DATABASE
         value: n8n
       - key: DB_POSTGRESDB_HOST
         value: postgres-host
       - key: DB_POSTGRESDB_PORT
         value: 5432
       - key: DB_POSTGRESDB_USER
         value: postgres-user
       - key: DB_POSTGRESDB_PASSWORD
         value: postgres-password
